#!/bin/bash

# Make a symlink to this script
# (or copy it) to /app/bin.

source /etc/profile.d/fh_path.sh
scriptname=${0##*/}
rundir=$( dirname $0 )
#
# remove local user-customisations to python behavior
unset PYTHONPATH
unset PYTHONUSERBASE
unset PYTHONHOME

ml Python/3.6.5-foss-2016b-fh1
python3 ${rundir}/${scriptname}.py $@
